import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NewJobFormProvider } from "@/components/new-job-form-provider";
import { QueryClientProvider } from "@/components/query-client-provider";
import { AuthProvider } from "@/components/auth-provider";
import { getUser } from "@/actions/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <AuthProvider initial={user}>
            <NewJobFormProvider>{children}</NewJobFormProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
